name: python
icon: python
title: Python

services:
- name: python
  title: Python
  service: python
  required: true
  links:
  - name: db
    service: postgres
  - name: sendmail
    service: mailpit

- name: nginx
  title: Nginx
  service: nginx
  required: true
  containers:
  - name: nginx
    env:
    - name: NGINX_VHOST_PRESET
      value: http-proxy
  links:
  - name: backend
    service: python

- name: postgres
  title: PostgreSQL
  service: postgres
  disabled: true  
  volumes:
  - name: data
    size: 20

- name: redis
  title: Redis
  service: redis
  disabled: true  

- name: mailpit
  title: Mailpit
  service: mailpit

- name: opensmtpd
  disabled: true
  title: OpenSMTPD
  service: opensmtpd
